language: python
python:  
  - "3.7"
env:
  - DJANGO=2.2

install:
  - pip install black
  - pip install importlib-metadata
  - pip install coverage
  - pip install django-crispy-forms==1.14.0
  - pip install flake8
  - pip install Django==2.2
  - pip install pytz==2022.4
  - pip install sqlparse==0.4.3
  - pip install coveralls

script:
  - black  ./
  - flake8 ./
  - coverage run BeHonest/manage.py test

after_success:
 coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYIDPROD
  secret_access_key: $SECRETACCESSKEYPROD
  region: "us-west-2"  
  app: "BeHonest-production"
  env: "BeHonest-production-env"
  bucket_name: "elasticbeanstalk-us-west-2-651033129971"
  on:
    branch: main